name: desafio_01

on:
  workflow_dispatch:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: false
        default: 'latest'
        type: string

jobs:
  pull_and_inspect_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkou
        uses: actions/checkout@v4

      - name: pull image ${{inputs.image_name}}:${{inputs.image_tag}}
        run: docker image pull ${{inputs.image_name}}:${{inputs.image_tag}}

      - name: show images
        run: docker image ls ${{inputs.image_name}}

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{inputs.image_name}}:${{inputs.image_tag}}
          only-severities: critical,high