name: Trabalho entre jobs

on: 
  workflow_dispatch

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere a versÃ£o do ubuntu
        run: cat /etc/os-release
      - name: Exibir mensagem
        run: echo "giropops strigus girus" > ${{github.workspace}}/mensagem.txt
      - uses: actions/upload-artifact@v4
        with:
          name: strigus-upload
          path: ${{github.workspace}}/mensagem.txt
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Verifica conteudo do dir
        run: ls -lha
      - uses: actions/download-artifact@v4
        with:
          name: strigus-upload
          path: strigus
      - name: Verifica conteudo do dir novamente
        run: ls -lha && ls ./strigus
      - name: move arquivo
        run: mv strigus/mensagem.txt . && rm -rf ./strigus
      - name: Verifica conteudo do dir novamente
        run: ls -lha
      - name: Acessa arquivo mensagem.txt
        run: cat mensagem.txt
