name: Trabalho entre steps

on: 
  workflow_dispatch

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Confere a versÃ£o do ubuntu
        run: cat /etc/os-release
      - name: Exibir mensagem
        run: echo "giropops strigus girus" > mensagem.txt
      - name: Qualquer outra coisa
        run: ls -lha
      - name: Ler conteudo do arquivo
        run: cat mensagem.txt