name: Trabalho entre jobs

on: 
  workflow_dispatch

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere a versÃ£o do ubuntu
        run: cat /etc/os-release
      - name: Exibir mensagem
        run: echo "giropops strigus girus" > mensagem.txt
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica conteudo do dir
        run: ls -lha
      - name: Acessa arquivo mensagem.txt
        run: cat mensagem.txt